.TH HEKATE 1 "June 2009"
.SH NAME
hekate \- a BitTorrent seeder
.SH SYNOPSIS
.B hekate
.IR option "... " directory ...
.SH DESCRIPTION
Hekate is a BitTorrent seeder, able to seed
thousands of torrents to thousands of peers.
.SH OPTIONS
.TP
.BI \-t
Do not contact any trackers.
.TP
.BI \-h
Do not participate in the DHT.
.TP
.BI \-4
Contact trackers over IPv4 only.
.TP
.BI \-6
Contact trackers over IPv6 only.
.TP
.BI \-p " port"
Specify the listening TCP port.
.TP
.BI \-N " max_unchoked"
Specify the maximum number of simultaneously unchoked peers (50 by
default).  The maximum number of connected peers will be set to 10 times
that.
.TP
.BI \-C " credit"
Specify the
.I initial credit
given to a peer, in bytes.  This is the amount that will be served to
a peer before it is considered for choking or dropping.  The default is
1048576 (1MB).
.TP
.BI \-T " time"
Specify the maximum time for which a peer can remain unchoked before it is
considered for choking or dropping.  The default is 300 (5 minutes).
.TP
.BI \-d " level"
Specify the debug level.  The default is 0.  A value of 4 will display
every BitTorrent message sent or received.
.TP
.IR directory ...
The list of directories in which
.B hekate
should (recursively) look for torrents.
.SH BUGS
Plenty.  This is experimental software, run at your own risk.
.SH SEE ALSO
.BR transmission (1),
.BR deluge (1),
.BR rtorrent (1).
.SH AUTHORS
Pejman Attar, Yoann Canal, Juliusz Chroboczek and Gabriel Kerneis.
